GOOGLE_API_KEY = "AIzaSyCAuomZVHlQLDdXeVeSebtJF6ZpD9j_cD4"
SUPABASE_URL = "https://ukqbbhwyivmdilalbyyl.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVrcWJiaHd5aXZtZGlsYWxieXlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEyNDExNTAsImV4cCI6MjA3NjgxNzE1MH0.MkHoZP2UnyvDZxl8Mc1o7rJhw4plDe6Bq0ygNIoVD9o"
TESSERACT_PATH = "C:\\Program Files\\Tesseract-OCR\\tesseract.exe"
LOG_LEVEL = "INFO"