GOOGLE_API_KEY = "AIzaSyCAuomZVHlQLDdXeVeSebtJF6ZpD9j_cD4"
TESSERACT_PATH = "C:\\Program Files\\Tesseract-OCR\\tesseract.exe"
LOG_LEVEL = "INFO"

[connections.supabase]
URL = "https://ukqbbhwyivmdilalbyyl.supabase.co"
KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVrcWJiaHd5aXZtZGlsYWxieXlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEyNDExNTAsImV4cCI6MjA3NjgxNzE1MH0.MkHoZP2UnyvDZxl8Mc1o7rJhw4plDe6Bq0ygNIoVD9o"
DATABASE = "postgres"
USER = "postgres.ukqbbhwyivmdilalbyyl"
PASSWORD = "oBa5YbFlmjf47PyC"
HOST = "aws-1-us-east-1.pooler.supabase.com"
PORT = "5432"