# Google APIs
GOOGLE_API_KEY = "AIzaSyCAuomZVHlQLDdXeVeSebtJF6ZpD9j_cD4"  # Chave da API do Google para todos os serviços

# Configurações do Tesseract OCR
# Para Windows (local)
TESSERACT_PATH = "C:\\Program Files (x86)\\Tesseract-OCR\\tesseract.exe"
TESSDATA_PREFIX = "C:\\Program Files (x86)\\Tesseract-OCR"

# Para Linux (Streamlit Cloud)
#TESSERACT_PATH = "/usr/bin/tesseract"

# Configurações de Log
LOG_LEVEL = "INFO"

# Configurações do FiscalValidatorAgent
[FISCAL_VALIDATOR]
cache_enabled = true
cache_dir = ".fiscal_cache"
cache_ttl_days = 30

# Supabase API Configuration (new format)
SUPABASE_URL = "https://ukqbbhwyivmdilalbyyl.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVrcWJiaHd5aXZtZGlsYWxieXlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEyNDExNTAsImV4cCI6MjA3NjgxNzE1MH0.MkHoZP2UnyvDZxl8Mc1o7rJhw4plDe6Bq0ygNIoVD9o"

# Database Connection (for migrations) - new format
HOST = "aws-1-us-east-1.pooler.supabase.com"
PORT = "5432"
DATABASE = "postgres"
USER = "postgres.ukqbbhwyivmdilalbyyl"
PASSWORD = "oBa5YbFlmjf47PyC"

# Legacy format for backward compatibility
[connections.supabase]
URL = "https://ukqbbhwyivmdilalbyyl.supabase.co"
KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVrcWJiaHd5aXZtZGlsYWxieXlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEyNDExNTAsImV4cCI6MjA3NjgxNzE1MH0.MkHoZP2UnyvDZxl8Mc1o7rJhw4plDe6Bq0ygNIoVD9o"
[connections.supabase.database]
HOST = "aws-1-us-east-1.pooler.supabase.com"
PORT = "5432"
DATABASE = "postgres"
USER = "postgres.ukqbbhwyivmdilalbyyl"
PASSWORD = "oBa5YbFlmjf47PyC"